### ISSUE TITLE
How do you make it work?

### ISSUE THREAD

**Issue by lexterror** [wallyhall/ksh-fire#1]
I'm trying to get it to work in ksh termux Android. Please let me know!

**Comment by lexterror** [comment]
Never mind. Thank you.

**Comment by wallyhall** [comment]
Hi, sorry for the delay.  Did you get it working?  I've not tested this script in a while - it may not work correctly on more recent versions of ksh, and I've never tested it on Android.  It uses some additional utilities to discover terminal width etc, which may not be available.

**Comment by lexterror** [comment]
Yes it works. Thank you. Also, I aas able to run Doom fire sdl2 on android with termux-x11. I just find that all doom fire variants are a bit boring/repetitive with the way main texture has been set up with the algorithm. I feel like adding a few more lines of code could make the fire more random/dynamic but im not a professional programmer and i dont have a lot of time to experiment. Also, Im really liking those 8-bit fireplace animations like the ones by Ted Martens and George Ford. The Martens one is available for download at itch.io. Thank you for answering.

**Comment by wallyhall** [comment]
Was there a particular interactivity you had in mind?  I'm happy to knock something up in JS (which might do more than 10fps! ... I'm really abusing the console/shell for these demos) with some mouse interaction etc.

**Comment by lexterror** [comment]
Ok so what i think would be really nice is a pixelized version of doom fire with a grid between 10x10 to 16x16 pixels but in full screen... kind of like pixel art. I think a lot of folks would enjoy it. You would need a small js engine for it though.

[flamesXfinal.txt](https://github.com/wallyhall/ksh-fire/files/13311129/flamesXfinal.txt)

I came up with that its an html feel free to run it

**Comment by wallyhall** [comment]
Your JS/HTML looks pretty close to that description - if you don't have the blurring div overlaying the canvas (and the browser is fullscreen).

![image](https://github.com/wallyhall/ksh-fire/assets/4852875/2e3b6beb-72a9-42f3-973b-adc7540bb03a)

**Comment by lexterror** [comment]
Ok did it :)

This is my PixelFire preview

[PixelFire.txt](https://github.com/wallyhall/ksh-fire/files/13311739/PixelFire.txt)

![pixelfirepreview](https://github.com/wallyhall/ksh-fire/assets/16135535/e4cf6529-9b06-4e6d-9632-e80ea274c0c9)

I'm going to literally make it 16x16 and add a log haha

**Comment by lexterror** [comment]
Ok this is my final version:

Thank you!

[PixelFire_1.0.txt](https://github.com/wallyhall/ksh-fire/files/13312466/PixelFire_1.0.txt)

![preview_JS-Pixel](https://github.com/wallyhall/ksh-fire/assets/16135535/31c000fd-e829-4b35-82b7-e9db8e012c9e)

**Comment by lexterror** [comment]
Wally, I wanted to share this with you, I wrote the whole thing from scratch with my own code:

http://alext.rf.gd

![Screenshot_20231205-074010](https://github.com/lexterror/Js-Pixel-Fireplace/assets/16135535/8aa842a5-d49e-4342-aeb2-b64259653200)

I really could not have done it without contributions like yours. Thank you!
